# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user', models.CharField(choices=[('dwzx', 'dwzx'), ('node', 'node')], default='普通用户', max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('rootpassword', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=1024)),
                ('item', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('group', models.CharField(choices=[('dev', '开发'), ('admin', '运维')], default='开发', max_length=20)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
